$(document).ready(function(){
    $('#menu_01').click(function(){ 
        $('html,body').animate({scrollTop:$('#story').offset().top},800)
  });
  $('#menu_02').click(function(){ 
        $('html,body').animate({scrollTop:$('#feature').offset().top},1200)
  });
  $('#menu_03').click(function(){ 
        $('html,body').animate({scrollTop:$('#links').offset().top},1600)
  });
});